### ISSUE TITLE
First touch on canvas always creates the same dot

### ISSUE THREAD

**Issue by testUserMachine1987** [eisukekusachi/HandDrawingSwiftMetal#1]
I've noticed that the first touch on the canvas seems to ignore the pressure and creates the same dot at the start of the stroke. Strokes that start with very low pressure then have this dot at the beginning. 
![IMG_0198](https://user-images.githubusercontent.com/1311419/180657983-c107ef26-0c28-4610-ad33-3bf0cc867e16.PNG)

**Comment by eisukekusachi** [comment]
I can reproduce the bug on my iPad + Apple Pencil. I didn't notice it because I only checked on my iPhone. I’ll fix it later. Thanks!

![IMG_0005](https://user-images.githubusercontent.com/51893896/181038944-43f52068-7dfb-419a-b4c9-7d97a97e5428.PNG)
![IMG_6842](https://user-images.githubusercontent.com/51893896/181038978-9abd9c50-7a56-4f0c-b23e-ab4123c1239f.PNG)

**Comment by eisukekusachi** [comment]
https://developer.apple.com/forums/thread/96700

**Comment by testUserMachine1987** [comment]
I've just had a look. The force from the Apple pencil always reports at 0.3333333333333333 for at least the first touch reading. And usually the second and third as well. Sometimes the fourth. 
The stroke objects produced by pencilkit don't have this issue so Apple probably corrects for that internally.  
Ignoring those first touches seems like a decent workaround. It doesn't lose any responsiveness when drawing. 
This is a really good brush engine. Good work.

**Comment by eisukekusachi** [comment]
I apologize for the mistake. The solution that did not use the initial value was not appropriate.

The issue with the incorrect opacity of the initial value was due to the use of estimated values. Since the Apple Pencil is a separate device from the iPad and sends data via Bluetooth, `UITouch` initially returns estimated values, and after the app receives the data, it returns the actual values. Developers need to use the actual values.

In the above PR, the issue is resolved by using `override func touchesEstimatedPropertiesUpdated(_ touches: Set<UITouch>)`.

![IMG_0062](https://github.com/user-attachments/assets/f14d1e8d-1a52-4bd3-965b-7aaa8c553d14)
